# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jiwon Lee
email: ljw00@kist.re.kr
# website: https://github.com/leejiwon1202

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: leejiwon1202
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: leejiwon1202
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: blog
  icon: fas fa-house
  url: https://happy-support.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a student researcher at KIST and Ph.D. student at [Yonsei University Theory of Computation Lab](https://toc.yonsei.ac.kr/) under the supervision of Prof. Yosub Han.   
  My primary research interest is Multimodal Deep Learning.   
# , especially 뭐시기 뭐시기. I am currently interested in @.   

content:
  - title: 📃 Publications
    layout: text
    content:
      [Fine-tuning Neural Network for Improving Video Classification Performance Using Vision Transfomer](https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11550771)   
      Published in Institute of Korean Electrical and Electronics Engineers, 2023   
      
  - title: 🏫 Education # Title for the section
    layout: list # Type of content section (list/text)
    content:  
      - layout: left
        title: Yonsei University
        caption: Mar 2024 - present
        sub_title: Ph.D. in Computer Science
        description: | # this will include new lines to allow paragraphs
          I am currently studying Multimodal Deep Learning.
      - layout: left
        title: Seokyeong University
        caption: Mar 2020 - Feb 2024
        sub_title: B.S. in Computer Engineering
        description: | # this will include new lines to allow paragraphs
          I took courses on programming languages, AI, algorithms, and other subjects.   
          I graduated with highest honor from the University of Science and Technology (GPA:4.45/4.50).   
          I studied computer vision as an undergraduate student researcher (Mar 2023 - Feb 2024). 
          
  - title: 💼 Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
        title: KIST
        # link_text: boringcompany.com
        sub_title: Student Researcher
        caption: Mar 2024 - present
        description: | # this will include new lines to allow paragraphs
            I am studying AI at the Center for Opto-Electronic Materials and Devices.
            I am responsible for researching artificial intelligence models required for project tasks and implementing programs.
      - layout: left
        title: Hdmedi
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: Dec 2022 - Jan 2023
        description: | # this will include new lines to allow paragraphs
            I crawled pharmaceutical data using Python libraries BeautifulSoup, Scrapy, and Selenium.   
            I preprocessed and analyzed data using SQL, and proceeded to input it into the company's database.

  - title: 🏆️ Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mini Drone Autonomous Flight Competition
        caption: Apr 2022 - Jul 2022
        link: https://github.com/leejiwon1202/2022_Drone_Competition_Doodoorone
        link_text: Competition Github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          The objective of this competition is for a drone programmed in MATLAB language to successfully navigate a given specification of a stadium.   
          Our team got silver award in autonomous flight and best technical presentation award.   

  - title: 💻 Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Web Project
        caption: Jun 2022 - Nov 2022
        link: https://github.com/leejiwon1202/2022_Web_Project_footprints
        link_text: Project Github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Our team created a webpage for sharing delivery fees among single-person households.   
          I was responsible for screen design and publishing, event handling, chat functionality using Socket, and address data processing using the Kakao Map API.   
      - layout: left
        title: Deep Learning Study
        caption: Jan 2022
        link: https://github.com/leejiwon1202/2022_DeepLearningStudy
        link_text: Study Github
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Students who are eager to delve deeper into deep learning participated in the study sessions, and we held weekly team presentations where each group summarized and presented what they had studied during the week.   
          We also conducted a project where team members collected pictures of rock-paper-scissors gestures to create a classification model with high accuracy.   
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 🚗 I was active as a member of the photo/travel club's organizing team (Mar 2023 - Dec 2023). 
      - 🏃 I really enjoy walking, running, and cycling.
      - 📚 I usually spend my free time reading books.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
