# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jiwon Lee
email: ljw00@kist.re.kr
# website: https://github.com/leejiwon1202

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: leejiwon1202
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: leejiwon1202
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: blog
  icon: fa-solid fa-house
  url: https://happy-support.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a student researcher at KIST and Ph.D. student at [Yonsei University Theory of Computation Lab](https://toc.yonsei.ac.kr/).   
  My primary research interest is Multimodal Deep Learning.   
# , especially 뭐시기 뭐시기. I am currently interested in @.   

content:
  - title: 🏫 Education # Title for the section
    layout: list # Type of content section (list/text)
    content:  
      - layout: left
        title: Yonsei University
        caption: Mar 2024 - present
        sub_title: Ph.D. in Computer Science
        description: | # this will include new lines to allow paragraphs
          I am studying multimodal under the guidance of Prof. Han.
      - layout: left
        title: Seokyeong University
        caption: Mar 2020 - Feb 2024
        sub_title: B.S. in Computer Engineering
        description: | # this will include new lines to allow paragraphs
          I have taken courses in programming languages, AI, algorithms, and other computer science subjects.   
          I graduated with highest honor from the University of Science and Technology (GPA:4.45/4.50).   
          I studied computer vision as an undergraduate student researcher (Mar 2023 - Feb 2024). 
          
  - title: 💼 Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hdmedi
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: Dec 2022 - Jan 2023
        description: | # this will include new lines to allow paragraphs
            I crawled pharmaceutical data using Python libraries BeautifulSoup, Scrapy, and Selenium.   
            I preprocessed and analyzed data using SQL, and proceeded to input it into the company's database.

  - title: 🏆️ Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2022 Mini Drone Autonomous Flight Competition
        link: https://github.com/leejiwon1202/2022_Drone_Competition_Doodoorone.git
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          The objective of this competition is for a drone programmed in MATLAB language to successfully navigate a given specification of a stadium.
          I got silver award in autonomous flight and best technical presentation award



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
